require 'test/unit'
$LOAD_PATH.unshift File.dirname(__FILE__)+'/../lib/'

require 'syncfiler'
require 'file_submission_server.rb'
require 'file_submission_client.rb'
# require 'db/file_info_db.rb'
require 'settings.rb'
require 'db/file_info.rb'
require 'db/name_info.rb'
